plugins {
	id 'java'
	id 'org.springframework.boot' version "${springBootVersion}"
	id 'io.spring.dependency-management' version "$springDependencyManagementVersion"
}

group = 'com.codfish'
version = '1.4.4'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}


configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// spring
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	//db
	implementation 'org.flywaydb:flyway-core:10.20.0'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql:10.20.0'
	runtimeOnly 'org.postgresql:postgresql'

	// annotations
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation "org.mapstruct:mapstruct:${mapstructVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

	// test
	testRuntimeOnly 'com.h2database:h2'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.security:spring-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.testcontainers:junit-jupiter'
	testImplementation 'org.testcontainers:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'

	//plantUml
	implementation "de.elnarion.util:plantuml-generator-util:${plantUml}"

	// pdf
	implementation 'com.github.librepdf:openpdf:1.3.30'
}
dependencyManagement {
	imports {
		mavenBom "org.testcontainers:testcontainers-bom:${testcontainersVersion}"
	}
}
tasks.withType(JavaCompile).configureEach {
	options.compilerArgs << "-Xlint:-deprecation"
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
}

jar {
	archiveFileName = project.hasProperty('customJarName') ? "${project.property('customJarName')}.jar" : "${project.name}-${project.version}.jar"
	manifest {
		attributes(
				'Main-Class': 'com.codfish.bikeSalesAndService.BikeSalesAndServiceApplication'
		)
	}
}

bootJar {
	archiveFileName = project.hasProperty('customJarName') ? "${project.property('customJarName')}.jar" : "${project.name}-${project.version}.jar"
}

compileJava.options.encoding = 'UTF-8'
